app_home_index:
    path:     /
    defaults: { _controller: AppBundle:Home:index }
app_home_ads:
    path:     /ads.html
    defaults: { _controller: AppBundle:Home:ads }
app_home_settings:
    path:     /settings.html
    defaults: { _controller: AppBundle:Home:settings }
app_home_notif_wallpaper:
    path:     /notif/wallpaper.html
    defaults: { _controller: AppBundle:Home:notifWallpaper }
app_home_notif_url:
    path:     /notif/url.html
    defaults: { _controller: AppBundle:Home:notifUrl }
app_home_notif_user_wallpaper:
    path:     /notif/user_wallpaper.html
    defaults: { _controller: AppBundle:Home:notifUserWallpaper }
app_home_notif_user:
    path:     /notif/user.html
    defaults: { _controller: AppBundle:Home:notifUser }
app_home_notif_category:
    path:     /notif/category.html
    defaults: { _controller: AppBundle:Home:notifCategory }
api_home_api_device:
    path:   /api/device/{tkn}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Home:api_device }
app_support_index:
    path:     /support/index.html
    defaults: { _controller: AppBundle:Support:index }
app_support_view:
    path:     /support/view/{id}.html
    defaults: { _controller: AppBundle:Support:view }
app_support_delete:
    path:     /support/delete/{id}.html
    defaults: { _controller: AppBundle:Support:delete }
api_support_add:
    path:     /api/support/add/{token}/{purchase}/
    defaults: { _controller: AppBundle:Support:api_add }
    methods: POST

app_home_tags_index:
    path:     /tags/index.html
    defaults: { _controller: AppBundle:Home:tags }
app_home_tags_delete:
    path: /tags/delete/{id}.html
    defaults: { _controller: AppBundle:Home:deletetag}
    requirements:
        id:  \d+
api_tags_all:
    path: /api/tags/all/{token}/{purchase}/
    defaults: { _controller: AppBundle:Category:api_tags}
api_home_first:
    path: /api/first/{token}/{purchase}/
    defaults: { _controller: AppBundle:Home:api_first}
#pack
app_pack_add:
    path: /pack/add.html
    defaults: { _controller: AppBundle:Pack:add}
app_pack_index:
    path: /pack/index.html
    defaults: { _controller: AppBundle:Pack:index}
app_pack_edit:
    path: /pack/edit/{id}.html
    defaults: { _controller: AppBundle:Pack:edit}
    requirements:
        id:  \d+
app_pack_delete:
    path: /pack/delete/{id}.html
    defaults: { _controller: AppBundle:Pack:delete}
    requirements:
        id:  \d+
api_pack_all:
    path:     /api/pack/all/{token}/{purchase}/
    defaults: { _controller: AppBundle:Pack:api_list }
#color 
app_color_add:
    path: /color/add.html
    defaults: { _controller: AppBundle:Color:add}
app_color_index:
    path: /color/index.html
    defaults: { _controller: AppBundle:Color:index}
app_color_edit:
    path: /color/edit/{id}.html
    defaults: { _controller: AppBundle:Color:edit}
    requirements:
        id:  \d+
app_color_delete:
    path: /color/delete/{id}.html
    defaults: { _controller: AppBundle:Color:delete}
    requirements:
        id:  \d+
app_color_up:
    path: /color/up/{id}.html
    defaults: { _controller: AppBundle:Color:up}
    requirements:
        id:  \d+
app_color_down:
    path: /color/down/{id}.html
    defaults: { _controller: AppBundle:Color:down}
    requirements:
        id:  \d+
api_color_list:
    path:     /api/color/all/{token}/{purchase}/
    defaults: { _controller: AppBundle:Color:api_list }
api_color_by:
    path:     /api/color/by/{id}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Color:api_by }
    requirements:
        id:  \d+ 
#slide
app_slide_add:
    path: /slide/add.html
    defaults: { _controller: AppBundle:Slide:add}
app_slide_index:
    path: /slide/index.html
    defaults: { _controller: AppBundle:Slide:index}
app_slide_edit:
    path: /slide/{id}.html
    defaults: { _controller: AppBundle:Slide:edit}
    requirements:
        id:  \d+
app_slide_delete:
    path: /slide/delete/{id}.html
    defaults: { _controller: AppBundle:Slide:delete}
    requirements:
        id:  \d+
app_slide_up:
    path: /slide/up/{id}.html
    defaults: { _controller: AppBundle:Slide:up}
    requirements:
        id:  \d+
app_slide_down:
    path: /slide/down/{id}.html
    defaults: { _controller: AppBundle:Slide:down}
    requirements:
        id:  \d+
api_slide_all:
    path:     /api/slide/all/{token}/{purchase}/
    defaults: { _controller: AppBundle:Slide:api_all }

#rate api 

api_rate_add:
    path:     /api/rate/add/{user}/{wallpaper}/{value}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_add_rate }
api_rate_get:
    path:     /api/rate/get/{user}/{wallpaper}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_get_rate }

#category
app_category_index:
    path: /category/index.html
    defaults: { _controller: AppBundle:Category:index}

app_category_add:
    path: /category/add.html
    defaults: { _controller: AppBundle:Category:add}

app_category_edit:
    path: /category/edit/{id}.html
    defaults: { _controller: AppBundle:Category:edit}
    requirements:
        id:  \d+

app_category_delete:
    path: /category/delete/{id}.html
    defaults: { _controller: AppBundle:Category:delete}
    requirements:
        id:  \d+

app_category_up:
    path: /category/up/{id}.html
    defaults: { _controller: AppBundle:Category:up}
    requirements:
        id:  \d+

app_category_down:
    path: /category/down/{id}.html
    defaults: { _controller: AppBundle:Category:down}
    requirements:
        id:  \d+
api_category_all:
    path:     /api/category/all/{token}/{purchase}/
    defaults: { _controller: AppBundle:Category:api_all }
api_category_popular:
    path:     /api/category/popular/{token}/{purchase}/
    defaults: { _controller: AppBundle:Category:api_popular }
#version
app_version_add:
    path: /version/add.html
    defaults: { _controller: AppBundle:Version:add}
app_version_index:
    path: /version/index.html
    defaults: { _controller: AppBundle:Version:index}
app_version_edit:
    path: /version/edit/{id}.html
    defaults: { _controller: AppBundle:Version:edit}
    requirements:
        id:  \d+
app_version_delete:
    path: /version/delete/{id}.html
    defaults: { _controller: AppBundle:Version:delete}
    requirements:
        id:  \d+
api_version_check:
    path: /api/version/check/{code}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Version:api_check}
    requirements:
        code:  \d+

#video

app_wallpaper_index:
    path: /wallpaper/index.html
    defaults: { _controller: AppBundle:Wallpaper:index}
app_video_edit:
    path: /video/{id}.html
    defaults: { _controller: AppBundle:Wallpaper:editVideo}
    requirements:
        id:  \d+
app_video_add:
    path: /video/add.html
    defaults: { _controller: AppBundle:Wallpaper:addVideo}
app_video_addurl:
    path: /video/addurl.html
    defaults: { _controller: AppBundle:Wallpaper:addVideoUrl}
app_video_editurl:
    path: /videourl/{id}.html
    defaults: { _controller: AppBundle:Wallpaper:editVideourl}
    requirements:
        id:  \d+

app_gif_add:
    path: /gif/add.html
    defaults: { _controller: AppBundle:Wallpaper:addGif}
app_gif_edit:
    path: /gif/{id}.html
    defaults: { _controller: AppBundle:Wallpaper:editGif}
    requirements:
        id:  \d+
app_image_add:
    path: /image/add.html
    defaults: { _controller: AppBundle:Wallpaper:addImage}

app_image_edit:
    path: /image/{id}.html
    defaults: { _controller: AppBundle:Wallpaper:editImage}
    requirements:
        id:  \d+
app_wallpaper_view:
    path: /wallpaper/view/{id}.html
    defaults: { _controller: AppBundle:Wallpaper:view}
    requirements:
        id:  \d+
app_wallpaper_reviews:
    path: /wallpaper/reviews.html
    defaults: { _controller: AppBundle:Wallpaper:reviews}
app_wallpaper_delete:
    path: /wallpaper/delete/{id}.html
    defaults: { _controller: AppBundle:Wallpaper:delete}
    requirements:
        id:  \d+
api_wallpaper_all:
    path:     /api/wallpaper/all/{order}/{page}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_all }
    requirements:
        page: \d+
api_wallpaper_my:
    path:     /api/wallpaper/my/{page}/{user}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_my }
    requirements:
        page: \d+
app_wallpaper_review:
    path: /wallpaper/reviewV/{id}.html
    defaults: { _controller: AppBundle:Wallpaper:review}
    requirements:
        id:  \d+


api_wallpaper_add_download:
    path:     /api/wallpaper/add/download/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_add_download }
api_wallpaper_add_set:
    path:     /api/wallpaper/add/set/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_add_set }
api_wallpaper_add_share:
    path:     /api/wallpaper/add/share/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_add_share }
api_wallpaper_add_view:
    path:     /api/wallpaper/add/view/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_add_view }
api_wallpaper_by_user:
    path:     /api/wallpaper/user/{page}/{user}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_by_user }
    requirements:
        user: \d+
        page: \d+

api_video_upload:
    path:     /api/video/upload/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_upload}
api_gif_upload:
    path:     /api/gif/upload/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_uploadGif}
api_image_upload:
    path:     /api/image/upload/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_uploadImage}
api_wallpaper_by_me:
    path:     /api/wallpaper/me/{page}/{user}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_by_me }
    requirements:
        user: \d+
        page: \d+

api_wallpaper_by_follow:
    path:     /api/wallpaper/by/follow/{page}/{user}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_by_follow }
    requirements:
        page: \d+
        user: \d+
api_wallpaper_by_category:
    path:     /api/wallpaper/category/{page}/{category}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_by_category }
    requirements:
        category: \d+
        page: \d+
api_wallpaper_by_random:
    path:     /api/wallpaper/random/{page}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_by_random }
    requirements:
        page: \d+
api_wallpaper_by_pack:
    path:     /api/wallpaper/pack/{page}/{pack}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_by_pack }
    requirements:
        pack: \d+
        page: \d+
api_wallpaper_by_color:
    path:     /api/wallpaper/color/{page}/{color}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_by_color }
    requirements:
        color: \d+
        page: \d+
api_wallpaper_by_query:
    path:     /api/wallpaper/query/{page}/{query}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_by_query }
    requirements:
        page: \d+
#not yet






#reactions 

api_video_add_like:
    path:     /api/video/add/like/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_add_like }
    
api_video_add_love:
    path:     /api/video/add/love/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_add_love }

api_video_add_angry:
    path:     /api/video/add/angry/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_add_angry }

api_video_add_sad:
    path:     /api/video/add/sad/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_add_sad }

api_video_add_haha:
    path:     /api/video/add/haha/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_add_haha }

api_video_add_woow:
    path:     /api/video/add/woow/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_add_woow }



api_video_delete_like:
    path:     /api/video/delete/like/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_delete_like }
    
api_video_delete_love:
    path:     /api/video/delete/love/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_delete_love }

api_video_delete_angry:
    path:     /api/video/delete/angry/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_delete_angry }

api_video_delete_sad:
    path:     /api/video/delete/sad/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_delete_sad }

api_video_delete_haha:
    path:     /api/video/delete/haha/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_delete_haha }

api_video_delete_woow:
    path:     /api/video/delete/woow/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_delete_woow }

#comment
app_comment_delete:
    path:     /comment/delete/{id}.html
    defaults: { _controller: AppBundle:Comment:delete }
    requirements:
        id:  \d+
app_comment_hide:
    path:     /comment/hide/{id}.html
    defaults: { _controller: AppBundle:Comment:hide }
    requirements:
        id:  \d+  
app_comment_index:
    path:     /comment/index.html
    defaults: { _controller: AppBundle:Comment:index }
api_comment_add:
    path:     /api/comment/add/{token}/{purchase}/
    defaults: { _controller: AppBundle:Comment:api_add }
    methods: POST
api_comment_list:
    path:     /api/comment/list/{id}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Comment:api_list }
    requirements:
        id:  \d+  
